name: Test Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies and Deploy get-function
        working-directory: cloud-resume-challenge/get-function
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests for get-function
        working-directory: cloud-resume-challenge/get-function
        run: python app.py  # Adjust based on your testing framework

      - name: Install Dependencies and Deploy put-function
        working-directory: cloud-resume-challenge/put-function
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Tests for put-function
        working-directory: cloud-resume-challenge/put-function
        run: python app.py  # Adjust based on your testing framework

