name: Test Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install Dependencies and Deploy get-function
        working-directory: cloud-resume-challenge/get-function
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          serverless deploy

      - name: Run Tests for get-function
        working-directory: cloud-resume-challenge/get-function
        run: python -m unittest discover tests  # Adjust based on your testing framework

      - name: Remove get-function
        working-directory: cloud-resume-challenge/get-function
        run: serverless remove

      - name: Install Dependencies and Deploy put-function
        working-directory: cloud-resume-challenge/put-function
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          serverless deploy

      - name: Run Tests for put-function
        working-directory: cloud-resume-challenge/put-function
        run: python -m unittest discover tests  # Adjust based on your testing framework

      - name: Remove put-function
        working-directory: cloud-resume-challenge/put-function
        run: serverless remove
