name: Python Unit Test

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies for get-function
        working-directory: get-function
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests in get-function
        working-directory: get-function
        run: python -m unittest discover -p 'test_*.py'

      - name: Install dependencies for put-function
        working-directory: put-function
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests in put-function
        working-directory: put-function
        run: python -m unittest discover -p 'test_*.py'



